name: Pack Documentation

on: [workflow_dispatch]

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set current date
        run: echo "CUR_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set sanitized name
        run: |
          SAN_NAME=$(echo "${{ github.repository }}" | tr '/' '-')
          echo "SAN_NAME=$SAN_NAME" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SAN_NAME }}-docs+${{ env.CUR_DATE }}
          path: ./docs/*